Repository framgia/sph-els-inventory, pull requests merged in 2022-08, with the labels that each got.

#2 [SPH-TASK] [FE] Create Welcome Back Page
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/welcome-page/index.css
  frontend/src/components/welcome-page/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  package-lock.json
Labels: Code Reviewer: Karlo

#3 [SPH-TASK] [FE] Create Nav Bar Component
  frontend/src/components/navbar/index.js
Labels: Code Reviewer: Karlo

#1 [BE] Setup backend
  inventory_backend/.env.example
  inventory_backend/api/__init__.py
  inventory_backend/api/admin.py
  inventory_backend/api/apps.py
  inventory_backend/api/migrations/0001_initial.py
  inventory_backend/api/migrations/__init__.py
  inventory_backend/api/models.py
  inventory_backend/api/serializers.py
  inventory_backend/api/tests.py
  inventory_backend/api/views.py
  inventory_backend/backend/__init__.py
  inventory_backend/backend/asgi.py
  inventory_backend/backend/settings.py
  inventory_backend/backend/urls.py
  inventory_backend/backend/wsgi.py
  inventory_backend/db.sqlite3
  inventory_backend/manage.py
Labels: Code Reviewer: Zion, Approved

#4 [FE] Layout for Register User Page
  frontend/src/pages/register-page/index.css
  frontend/src/pages/register-page/index.js
Labels: Code Reviewer: Karlo

#5 READ items in Database
  inventory_backend/api/serializers.py
  inventory_backend/db.sqlite3
Labels: For review, Code Reviewer: Zion, Approved

#7 [FE] Layout for Dashboard Page
  frontend/src/App.js
  frontend/src/pages/dashboard/components/AppHeader.js
  frontend/src/pages/dashboard/components/TodoItems.js
  frontend/src/pages/dashboard/index.css
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/register/index.css
  frontend/src/pages/register/index.js
  frontend/src/pages/welcome/index.css
  frontend/src/pages/welcome/index.js
Labels: Code Reviewer: Zion, Approved

#10 [FE] Implement Add User Confirmation Modal
  frontend/package-lock.json
  frontend/package.json
  frontend/src/modals/add-user/index.js
  frontend/src/pages/register/index.js
Labels: Code Reviewer: Zion, Approved

#8 [FE] Layout for Add Item Page
  frontend/src/App.js
  frontend/src/components/button/index.css
  frontend/src/components/button/index.js
  frontend/src/components/dropdown/index.css
  frontend/src/components/dropdown/index.js
  frontend/src/components/input-text-field/index.css
  frontend/src/components/input-text-field/index.js
  frontend/src/components/inputdate/index.css
  frontend/src/components/inputdate/index.js
  frontend/src/pages/add-item/index.css
  frontend/src/pages/add-item/index.js
Labels: Code Reviewer: Karlo

#11 [FE] Implement Delete Item Confirmation Modal
  frontend/package-lock.json
  frontend/package.json
  frontend/src/modals/delete-item/index.js
  frontend/src/pages/dashboard/components/TodoItems.js
Labels: Code Reviewer: Zion, Approved

#12 [FE] Layout for Users Page
  frontend/src/App.js
  frontend/src/components/navbar/index.js
  frontend/src/pages/dashboard/index.css
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/display-users/components/displayUserList.js
  frontend/src/pages/display-users/index.js
Labels: For review, Code Reviewer: Zion

#14 [FE] Implement Delete User Confirmation Modal
  frontend/src/modals/delete-user/index.css
  frontend/src/modals/delete-user/index.js
  frontend/src/pages/display-users/components/DisplaysUserList.js
  frontend/src/pages/display-users/index.js
Labels: Code Reviewer: Zion, Approved

#15 [FE] Implement Edit User Confirmation Modal
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/global.css
  frontend/src/modals/edit-user/index.js
  frontend/src/pages/add-item/index.js
  frontend/src/pages/edit-user-page/index.css
  frontend/src/pages/edit-user-page/index.js
Labels: Code Reviewer: Karlo

#16 Added Page Routing in Welcome, Register, Dashboard, Display User page
  frontend/src/App.js
  frontend/src/components/navbar/index.js
  frontend/src/pages/add-item/index.js
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/display-users/components/DisplaysUserList.js
  frontend/src/pages/display-users/index.js
  frontend/src/pages/welcome/index.js
  inventory_backend/.gitignore
  inventory_backend/api/serializers.py
Labels: Code Reviewer: Karlo

#17 Integrated BE to FE for Register/Add User with modal
  frontend/src/App.js
  frontend/src/handler.js
  frontend/src/modals/add-user/index.js
  frontend/src/pages/add-item/index.js
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/display-users/index.js
  frontend/src/pages/register/index.js
Labels: Code Reviewer: Zion, Approved

#18 Can view list of added users in List of Users
  frontend/src/pages/display-users/components/DisplaysUserList.js
Labels: Code Reviewer: Zion, Approved

#19 Can Delete or Edit User from List of Users Page
  frontend/src/modals/delete-user/index.js
  frontend/src/modals/edit-user/index.js
  frontend/src/pages/display-users/components/DisplaysUserList.js
  frontend/src/pages/edit-user/index.js
Labels: Code Reviewer: Zion, Approved

#20 [FE] Improved UI in some pages.
  frontend/src/App.js
  frontend/src/components/DropDownMenu/index.css
  frontend/src/components/DropDownMenu/index.js
  frontend/src/components/InputText/index.css
  frontend/src/components/InputText/index.js
  frontend/src/components/button/index.css
  frontend/src/global.css
  frontend/src/modals/add-user/index.js
  frontend/src/modals/edit-user/index.js
  frontend/src/pages/add-item/index.css
  frontend/src/pages/add-item/index.js
  frontend/src/pages/dashboard/components/AppHeader.js
  frontend/src/pages/dashboard/components/TodoItems.js
  frontend/src/pages/dashboard/index.css
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/display-users/components/DisplaysUserList.js
  frontend/src/pages/display-users/index.js
  frontend/src/pages/edit-item/index.css
  frontend/src/pages/edit-item/index.js
  frontend/src/pages/edit-user/index.css
  frontend/src/pages/edit-user/index.js
  frontend/src/pages/register/index.css
  frontend/src/pages/register/index.js
  frontend/src/pages/welcome/index.css
  frontend/src/pages/welcome/index.js
Labels: Code Reviewer: Zion, Approved

#21 [FE/BE] Integrate Item(CRUD)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/modals/delete-item/index.css
  frontend/src/modals/delete-item/index.js
  frontend/src/modals/edit-item/index.js
  frontend/src/pages/add-item/index.js
  frontend/src/pages/dashboard/components/TodoItems.js
  frontend/src/pages/dashboard/index.js
  frontend/src/pages/edit-item/index.js
  inventory_backend/api/admin.py
  inventory_backend/api/models.py
  inventory_backend/api/serializers.py
  inventory_backend/api/views.py
  inventory_backend/backend/urls.py
Labels: Code Reviewer: Zion, Approved

#22 Added response after Add or Edit User
  frontend/src/modals/add-user/index.js
  frontend/src/modals/edit-user/index.js
Labels: Code Reviewer: Zion, Approved

#23 [FE] Improved UI Design: Navbar, Edit Item, Add Item
  frontend/src/components/button/index.css
  frontend/src/components/navbar/index.css
  frontend/src/components/navbar/index.js
  frontend/src/global.css
  frontend/src/modals/add-user/index.js
  frontend/src/modals/edit-item/index.js
  frontend/src/pages/add-item/index.css
  frontend/src/pages/add-item/index.js
  frontend/src/pages/dashboard/index.css
  frontend/src/pages/edit-item/index.css
  frontend/src/pages/edit-item/index.js
  frontend/src/pages/edit-user/index.css
  frontend/src/pages/edit-user/index.js
  frontend/src/pages/register/index.css
  frontend/src/pages/register/index.js
Labels: Code Reviewer: Zion, Approved

#24 Can reserve and delete reservations inside items in click, Added Reservation Page
  frontend/src/App.js
  frontend/src/modals/delete-item/index.js
  frontend/src/modals/delete-user/index.js
  frontend/src/pages/dashboard/components/TodoItems.js
  frontend/src/pages/dashboard/index.css
  frontend/src/pages/reservation/index.css
  frontend/src/pages/reservation/index.js
  inventory_backend/api/admin.py
  inventory_backend/api/models.py
  inventory_backend/api/serializers.py
Labels: For review, Code Reviewer: Zion

#25 Fixed some bugs and improved some pages.
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo128.png
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/src/modals/add-user/index.js
  frontend/src/modals/edit-item/index.js
  frontend/src/modals/edit-user/index.js
  frontend/src/pages/add-item/index.css
  frontend/src/pages/add-item/index.js
  frontend/src/pages/dashboard/components/TodoItems.js
  frontend/src/pages/edit-item/index.js
  frontend/src/pages/reservation/index.js
Labels: Code Reviewer: Zion, Approved
